# Generated by Django 5.1.1 on 2024-10-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'common_numbers',
            },
        ),
        migrations.CreateModel(
            name='CommonYears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'common_years',
            },
        ),
        migrations.CreateModel(
            name='HighProbabilityRealUsernames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('search_result_title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'high_probability_real_usernames',
            },
        ),
        migrations.CreateModel(
            name='HighRatedUnames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'high_rated_unames',
            },
        ),
        migrations.CreateModel(
            name='HighRatedUnamesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'high_rated_unames_history',
            },
        ),
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10)),
                ('no_of_letters', models.IntegerField(db_column='NoOfLetters')),
            ],
            options={
                'db_table': 'names',
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10)),
                ('no_of_letters', models.IntegerField(db_column='NoOfLetters')),
            ],
            options={
                'db_table': 'words',
            },
        ),
    ]
